In [1]:
import pandas as pd
import numpy as np

In [2]:
# pd.Series() - 1D data with an index

total_bill = [4700, 8000, 1200, 500]
s = pd.Series(total_bill, index=['mon', 'tue', 'wed', 'fri'])
print(s)
print(type(s))

mon    4700
tue    8000
wed    1200
fri     500
dtype: int64
<class 'pandas.Series'>

In [3]:
# pd.DataFrame() - 1D data with an index
restaurant_data = {
    'Table_No': [12, 14, 15],
    'Bill_Amount': [1250, 890, 2400],
    'Waiter_Name': ['Amit', 'Priya' , 'Rahul']
}

df = pd.DataFrame(restaurant_data)

print(df)
print(type(df))

print(df['Bill_Amount'])
print(type(df['Bill_Amount']))

   Table_No  Bill_Amount Waiter_Name
0        12         1250        Amit
1        14          890       Priya
2        15         2400       Rahul
<class 'pandas.DataFrame'>
0    1250
1     890
2    2400
Name: Bill_Amount, dtype: int64
<class 'pandas.Series'>

In [4]:
labels = [45, 30, 15, 60]

In [5]:
shoes_data = {
    'Brand': ['Nike', 'Puma', 'Campus'],
    'Price': [5250, 3890, 2400],
    'In_Stock': [True, False , True]
}

df = pd.DataFrame(shoes_data)

print(df)

    Brand  Price  In_Stock
0    Nike   5250      True
1    Puma   3890     False
2  Campus   2400      True

In [6]:
print(df.values)
# print(type(df.values))

[['Nike' 5250 True]
 ['Puma' 3890 False]
 ['Campus' 2400 True]]

In [7]:
df = pd.read_csv("tip.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'tip.csv'

In [ ]:
df.head(20)

    Brand  Price  In_Stock
0    Nike   5250      True
1    Puma   3890     False
2  Campus   2400      True

In [ ]:
df.tail(20)

     total_bill   tip     sex smoker   day    time  size
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.sample()

    total_bill   tip     sex smoker  day    time  size
14       14.83  3.02  Female     No  Sun  Dinner     2

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
# value_counts(), unique(), nunique()
print(df['day'].value_counts())
print(df['day'].unique())
print(df['day'].nunique())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str
4