In [109]:
import numpy as np
import pandas as pd

titanic = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/PANDAS/Titanic-Dataset.csv")
tip = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/PANDAS/tip.csv")

print(tip.shape, titanic.shape)

(244, 7) (891, 12)

In [110]:
#Q1 which passenger paid the hhighest fare in each class, and what was their name?

In [111]:
# tip.groupby('column')
# tip.groupby('column').size()
# tip.groupby('column')['other'].mean()

# tip.groupby('day')
tip.groupby('day').size()
# tip.groupby('day')['tip'].mean()

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

In [112]:
#how many bills on each day

# tip.groupby("day").size()
tip.groupby('day')['tip'].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [113]:
# tip.groupby('day')['tip'].mean()
tip.groupby('day')['tip'].mean().round(2)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [114]:
# average tip on each day

In [115]:
# make a tip_pct column , then average it per day
tip['tip_pct'] = round(tip['tip']/tip['total_bill']*100, 2)
tip.head(2)
tip.groupby('day')["tip_pct"].mean().round(2)

day
Fri     16.99
Sat     15.31
Sun     16.69
Thur    16.13
Name: tip_pct, dtype: float64

In [116]:
# tip.groupby('day').mean(numeric_only=True)
tip.groupby('day').mean(numeric_only=True)['tip'] #aggregate first pick after

# tip.groupby('day').mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [117]:
tip.groupby('day')['tip'].mean() #pick before then aggregate

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [118]:
# Bigger table, bigger tip. what happens to the tip percentage as the party grows - up, downor flat?

tip.groupby('size')['tip_pct'].mean().round(1)

size
1    21.7
2    16.6
3    15.2
4    14.6
5    14.2
6    15.6
Name: tip_pct, dtype: float64

In [119]:
#average bill for each party size

tip.groupby('size')['total_bill'].mean()

size
1     7.242500
2    16.448013
3    23.277632
4    28.613514
5    30.068000
6    34.830000
Name: total_bill, dtype: float64

In [120]:
tip.head(1)

   total_bill   tip     sex smoker  day    time  size  tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2     5.94

In [121]:
titanic.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [122]:
#1.1 the company report class first class "somewhat safer" . Find the survial rate of each class and say in one line whether "somewhat" is honest.

titanic.groupby('Pclass')['Survived'].mean().round(2)*100

Pclass
1    63.0
2    47.0
3    24.0
Name: Survived, dtype: float64

In [ ]:
# Average fair paid in each class
titanic.groupby('Pclass')['Fare'].mean()
titanic.groupby('Pclass')['Fare'].mean().round(2)*100

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [126]:
#Passenegers per boarding port , and the average age of each group

titanic.groupby("Embarked")['Age'].mean()

Embarked
C    30.814769
Q    28.089286
S    29.445397
Name: Age, dtype: float64